filepaths:
  continue_from_checkpoint: false
  out_dir: '../outputs'
  train_set: '../filepath'
  val_set: '../filepath'
  log_level: 'info'

params: 
  seed: 42
  nx: 128
  Lx: 6.283185307179586  # 2π
  beta: 2.5
  kmin: 10.0
  kmax: 10.0
  nz: 1
  # multi-layer model parameters (only used if nz>1)
  Lz: 50
  rek: 5.787e-7 # this might balls up with the number stuff - check if i should remove config file and just yaml it 
  rd: 15.0
  delta: 0.25
  U1: 0.0
  U2: 0.0
  hr_nx: 128

plotting:
  nsteps: 100000
  dt: 0.041
  cadence: 100
  animate: ['PV']
  final: ['drift']
  auto_dt: true
  njets: 16
  spinup: 100000
  cfl: 0.5


forcing:
  k_f: 8.0           # central forcing wavenumber
  k_width: 2.0       # width of the ring
  epsilon: 0.001     # energy injection rate

ml:
  enabled: true
  model_type: unet
  device: 'cpu' # 'cpu' or 'gpu' <-- gotta be careful here w cuda supported jaxlib. 
  use_float64: false
  n_epochs: 5
  n_train: 7
  n_test: 3
  optimiser: AdamW
  n_batches: 10
  batch_steps: 10 
  batch_size: 64
  learning_rate: 0.0005


architectures:
  cnn:
    seed: 42
    nlayers: 3
    width: 64
    kernel_size: 3
  zero:
    exists: true
