filepaths:
  continue_from_checkpoint: false
  out_dir: '../outputs'
  train_set: '../filepath'
  val_set: '../filepath'
  log_level: 'info'

params: 
  seed: 42
  nx: 128
  Lx: 6.283185307179586  # 2π
  beta: 5
  kmin: 3.0
  kmax: 10.0
  n_layers: 2  # 1 for single-layer, 2 for two-layer model
  # Two-layer model parameters (only used if n_layers == 2)
  Lz: 50
  rek: 5.787e-7 # this might balls up with the number stuff - check if i should remove config file and just yaml it 
  rd: 15.0
  delta: 0.25
  U1: 0.025
  U2: 0.0

plotting:
  nsteps: 10000
  dt: 0.0006
  cadence: 100
  spinup: 0
  animate: [energy]
  final: []
  stepper: AB3Stepper
  auto_dt: false
  cfl: 0.1


forcing:
  k_f: 8.0           # central forcing wavenumber
  k_width: 2.0       # width of the ring
  epsilon: 0.001     # energy injection rate

ml:
  enabled: true
  model: zero
  spin_up: 10.0
  input_channels:
  output_channels: 
  num_epochs: 10
  optimiser: AdamW
  batches_per_epoch: 100
  batch_steps: 10 # not so sure about these two 
  batch_size: 8
  learning_rate: 0.0005
  lr_schedule: idk rn
  end_lr: yeha fiuck knows